# MEXC Exchange Configuration
# YAML-based configuration for MEXC cryptocurrency trading

# Environment settings
environment:
  name: dev  # dev, prod, test
  debug: true
  log_level: DEBUG  # CRITICAL, ERROR, WARNING, INFO, DEBUG

# MEXC Exchange API settings
mexc:
  api_key: "mx0vgl6pxdKU8DNcIT"  # Your MEXC API key
  secret_key: "200bba9bffc24768a6899d9b79320f71"  # Your MEXC secret key

# Network configuration
network:
  request_timeout: 10.0  # seconds
  connect_timeout: 5.0   # seconds
  max_retries: 3
  retry_delay: 1.0       # seconds

# Rate limiting
rate_limiting:
  mexc_requests_per_second: 18  # Conservative limit for MEXC

# WebSocket settings
websocket:
  connect_timeout: 10.0      # seconds
  heartbeat_interval: 30.0   # seconds
  max_reconnect_attempts: 10
  reconnect_delay: 5.0       # seconds