# CEX Arbitrage Engine Configuration
# YAML-based configuration for multi-exchange cryptocurrency trading

# Environment settings
environment:
  name: dev  # dev, prod, test
  debug: true
  log_level: DEBUG  # CRITICAL, ERROR, WARNING, INFO, DEBUG

# MEXC Exchange API settings
mexc:
  api_key: "mx0vgl6pxdKU8DNcIT"  # Your MEXC API key
  secret_key: "200bba9bffc24768a6899d9b79320f71"  # Your MEXC secret key
  base_url: "https://api.mexc.com"
  websocket_url: "wss://wbs-api.mexc.com/ws"

# Gate.io Exchange API settings
gateio:
  api_key: "9c83ff595ce55ae4fc83c08002bde62f"  # Your Gate.io API key (empty for public-only access)
  secret_key: "80d24f9870773ca69eb7988f7f6dd0b5f938aeaae6e41028522e89cfb1d5e236"  # Your Gate.io secret key (empty for public-only access)
  base_url: "https://api.gateio.ws/api/v4"  # Production URL
  websocket_url: "wss://api.gateio.ws/ws/v4/"  # Production WebSocket URL
  testnet_base_url: "https://api-testnet.gateapi.io/api/v4"  # Testnet URL
  testnet_websocket_url: "wss://ws-testnet.gate.com/v4/ws/spot"  # Testnet WebSocket URL

# Network configuration
network:
  request_timeout: 10.0  # seconds
  connect_timeout: 5.0   # seconds
  max_retries: 3
  retry_delay: 1.0       # seconds

# Rate limiting
rate_limiting:
  mexc_requests_per_second: 18  # Conservative limit for MEXC
  gateio_requests_per_second: 15  # Conservative limit for Gate.io (200/10s = 20, but use 15)

# WebSocket settings
websocket:
  connect_timeout: 10.0      # seconds
  heartbeat_interval: 30.0   # seconds
  max_reconnect_attempts: 10
  reconnect_delay: 5.0       # seconds

# HFT Arbitrage Engine Configuration
arbitrage:
  # Engine settings
  engine_name: "hft_arbitrage_main"
  enabled_opportunity_types:
    - "SPOT_SPOT"
    - "SPOT_FUTURES_HEDGE"
  enabled_exchanges:
    - "MEXC"
    - "GATEIO"

  # Performance settings (HFT targets)
  target_execution_time_ms: 30      # Target <50ms for HFT compliance
  opportunity_scan_interval_ms: 100  # Scan every 100ms
  position_monitor_interval_ms: 1000 # Monitor positions every 1s
  balance_refresh_interval_ms: 5000  # Refresh balances every 5s
  market_data_staleness_ms: 100     # Max 100ms data age for HFT

  # Risk management limits
  risk_limits:
    max_position_size_usd: 5000.0      # Maximum single position size
    max_total_exposure_usd: 25000.0    # Maximum total exposure across all positions
    max_exchange_exposure_usd: 15000.0 # Maximum exposure per exchange
    max_symbol_exposure_usd: 10000.0   # Maximum exposure per trading pair
    max_daily_loss_usd: 2500.0         # Maximum daily loss threshold
    max_single_loss_usd: 500.0         # Maximum loss per single arbitrage
    min_profit_margin_bps: 50          # Minimum 0.5% profit margin
    stop_loss_threshold_bps: 200       # 2% stop loss threshold
    max_execution_time_ms: 45000       # Maximum 45 second execution time
    max_slippage_bps: 25               # Maximum 0.25% slippage
    max_partial_fill_ratio: 0.1        # Maximum 10% partial fill ratio
    max_concurrent_operations: 3       # Maximum concurrent arbitrage operations
    max_price_deviation_bps: 100       # Maximum 1% price deviation from fair value
    min_market_depth_usd: 50000.0      # Minimum $50k order book depth required
    max_spread_bps: 500                # Maximum 5% bid-ask spread tolerance
    volatility_circuit_breaker_bps: 1000 # 10% volatility circuit breaker
    max_recovery_attempts: 3           # Maximum position recovery attempts
    recovery_timeout_seconds: 300      # 5 minute recovery timeout
    emergency_close_threshold_bps: 500 # 5% emergency position close threshold

  # Safety features
  enable_risk_checks: true          # Enable real-time risk validation
  enable_circuit_breakers: true     # Enable automated circuit breakers
  enable_websocket_feeds: true      # Use WebSocket for real-time data
  websocket_fallback_to_rest: true  # Fallback to REST if WebSocket fails
  enable_dry_run: true              # DRY RUN MODE: Default enabled for safety
  enable_detailed_logging: true     # Comprehensive operation logging
  enable_performance_metrics: true  # Detailed performance tracking
  enable_recovery_mode: true        # Automatic position recovery

  # Exchange-specific configurations
  exchange_configs:
    MEXC:
      # MEXC-specific settings can be added here
      priority: 1  # Exchange priority for execution
    GATEIO:
      # Gate.io-specific settings can be added here
      priority: 2  # Exchange priority for execution