# =============================================================================
# Local Monitoring Stack for Remote CEX Arbitrage Database
# =============================================================================
# This file creates Grafana and PgAdmin on your local machine to connect
# to the remote production database on 31.192.233.13

version: '3.8'

services:
  # Local Grafana for remote monitoring
  grafana_local:
    image: grafana/grafana:latest
    container_name: arbitrage_grafana_local
    ports:
      - "3000:3000"
    environment:
      # Admin credentials
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-local_grafana_2024}
      
      # Security settings
      GF_SECURITY_DISABLE_GRAVATAR: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      
      # Use internal SQLite database for Grafana configuration
      # External database will be added as a data source via provisioning
      
      # Performance settings
      GF_LOG_LEVEL: info
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
      
      # Server settings
      GF_SERVER_ROOT_URL: "http://localhost:3000"
      GF_SERVER_SERVE_FROM_SUB_PATH: "false"
    
    volumes:
      - grafana_local_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    
    restart: unless-stopped
    
    # Resource limits for local use
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # Local PgAdmin for remote database management
  pgadmin_local:
    image: dpage/pgadmin4:latest
    container_name: arbitrage_pgadmin_local
    ports:
      - "8080:80"
    environment:
      # Admin credentials
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@localhost.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-local_pgadmin_2024}
      
      # Configuration
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      PGADMIN_CONFIG_LOGIN_BANNER: '"Local PgAdmin - Remote CEX Arbitrage DB"'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: '30'
      PGADMIN_DISABLE_POSTFIX: 'True'
      GUNICORN_TIMEOUT: '60'
    
    volumes:
      - pgadmin_local_data:/var/lib/pgadmin
      - ./pgadmin/servers-remote.json:/pgadmin4/servers.json:ro
    
    restart: unless-stopped
    
    # Resource limits for local use
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'

volumes:
  grafana_local_data:
  pgadmin_local_data:

# No networks needed - connecting to external database