# Simple Arbitrage PoC Configuration
# Minimal configuration for testing arbitrage opportunities

arbitrage:
  # Trading symbol (use underscore format for Gate.io compatibility)
  symbol: "ETH_USDT"
  
  # Spread thresholds (percentages, not basis points)
  entry_threshold_pct: 0.06  # 0.06% minimum spread to enter
  exit_threshold_pct: 0.03   # 0.03% spread to exit position
  
  # Position sizing
  position_size: 1.0  # Position size in base currency (ETH)
  
  # Monitoring settings
  check_interval_seconds: 3  # How often to check for opportunities
  monitoring_duration_minutes: 10  # How long to run monitoring

# Exchange API endpoints (read-only, no authentication required for PoC)
exchanges:
  mexc:
    spot_book_ticker_url: "https://api.mexc.com/api/v3/ticker/bookTicker"
    symbol_format: "ETHUSDT"  # No underscore
    
  gateio:
    futures_book_ticker_url: "https://api.gateio.ws/api/v4/futures/usdt/book_tickers"
    symbol_format: "ETH_USDT"  # With underscore

# Logging configuration
logging:
  level: "INFO"  # DEBUG for more verbose output
  format: "%(asctime)s - %(levelname)s - %(message)s"

# PoC validation settings
validation:
  # Test data for manual verification
  test_spreads:
    profitable_spot_to_futures: 0.08  # 0.08% spread
    profitable_futures_to_spot: 0.07  # 0.07% spread
    unprofitable_spread: 0.02         # 0.02% spread (below threshold)
  
  # Expected behavior
  expected_entry_signals: 2     # Both directions above threshold
  expected_no_entry_signals: 1  # One direction below threshold