# AlertManager Configuration for HFT Arbitrage Engine
# Configured for critical trading alerts with appropriate routing

global:
  # Default SMTP settings (configure as needed)
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@hft-arbitrage.local'
  
  # Slack settings (optional - configure webhook_url)
  # slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

# Define notification templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing rules for different alert types
route:
  group_by: ['alertname', 'severity', 'component']
  group_wait: 10s        # Wait before sending initial notification
  group_interval: 10s    # Wait before sending notifications for same group
  repeat_interval: 1h    # Repeat notifications interval
  receiver: 'default'    # Default receiver
  
  # Specific routing for different severity levels
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 1s
      repeat_interval: 5m
      
    # Warning alerts - less frequent
    - match:
        severity: warning  
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m
      
    # System component specific routing
    - match:
        component: execution
      receiver: 'execution-alerts'
      group_wait: 5s
      repeat_interval: 10m

# Receiver definitions
receivers:
  # Default receiver (console logging)
  - name: 'default'
    # Add your preferred notification method here
    
  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    # Email notification (configure SMTP settings above)
    # email_configs:
    #   - to: 'admin@company.com'
    #     subject: '🚨 CRITICAL: HFT Arbitrage Alert'
    #     body: |
    #       Alert: {{ .GroupLabels.alertname }}
    #       Severity: {{ .GroupLabels.severity }}
    #       Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
    #       Time: {{ .GroupLabels.StartsAt }}
    
    # Slack notification (configure webhook above)
    # slack_configs:
    #   - channel: '#hft-alerts'
    #     color: 'danger'
    #     title: '🚨 Critical HFT Alert'
    #     text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    
    # Webhook for custom integrations
    webhook_configs:
      - url: 'http://localhost:8080/alerts/critical'
        send_resolved: true
        
  # Warning alerts - less urgent notifications  
  - name: 'warning-alerts'
    # email_configs:
    #   - to: 'monitoring@company.com'
    #     subject: '⚠️  WARNING: HFT Arbitrage Alert'
    #     body: |
    #       Alert: {{ .GroupLabels.alertname }}
    #       Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
    
    webhook_configs:
      - url: 'http://localhost:8080/alerts/warning'
        send_resolved: true
        
  # Execution-specific alerts
  - name: 'execution-alerts'
    webhook_configs:
      - url: 'http://localhost:8080/alerts/execution'
        send_resolved: true

# Inhibition rules - prevent spam
inhibit_rules:
  # Inhibit warning if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'component']
    
  # Inhibit system alerts if engine is down
  - source_match:
      alertname: 'ArbitrageEngineDown'
    target_match_re:
      alertname: '(WebSocketDisconnected|HighOrderFailureRate|LowOpportunityDetection)'