apiVersion: 1

datasources:
  - name: PostgreSQL-Arbitrage
    type: postgres
    url: database:5432
    database: arbitrage_data
    user: arbitrage_user
    secureJsonData:
      password: dev_password_2024
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500  # PostgreSQL 15
      timescaledb: true
    editable: true
    isDefault: true