apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: database:5432
    database: arbitrage_data
    user: readonly_user
    secureJsonData:
      password: readonly_password_2024
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
